config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :details, only: [:edit, :update, :show]

  get '/new_invoices_sum', to: 'charts#new_invoices_sum'
  get '/new_invoices_count', to: 'charts#new_invoices_count'
  get '/new_invoices_company', to: 'charts#new_invoices_company'
  get '/new_invoices_sum_count', to: 'charts#new_invoices_sum_count'


  root 'pages#home'

  get '/test', to: 'pages#test'

  resources :invoices do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  def self.delete_old
    @old_invoice = Invoice.where('date < ?', 30.days.ago)
    @old_invoice.delete_all
  end

  has_attached_file :image
  has_attached_file :resource

  belongs_to :user

  validates_attachment :image, presence: true,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
  message: "Only images allowed!"

  validates_attachment :resource, presence: true,
  content_type: { content_type: "application/pdf" },
  message: "Only PDF allowed!"
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  def index
    @search = Invoice.ransack(params[:q])
    @invoices = @search.result
  end

  def search
    index
    render :index
  end

  def new
    @invoice = Invoice.new
  end

  def create
    @invoice = Invoice.new(invoices_params)
    if @invoice.save
      flash[:success] = "Invoice successfully created"
      redirect_to invoices_path
    else
      render 'new'
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

  def update
    @invoice = Invoice.find(params[:id])
    if @invoice.update(invoices_params)
      flash[:success] = "Invoice successfully updated"
      redirect_to invoices_path
    else
      flash[:danger] = "Invoice was not updated"
      render 'edit'
    end
  end



  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy
    redirect_to invoices_path
  end

  private
  def invoices_params
    params.require(:invoice).permit(:amount, :company, :contragent, :currency, :date, :image, :resource)
  end
end

app/views/invoices/_data.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= line_chart new_invoices_sum_path, label: 'Faturamento [valores em R$]', ytitle: 'Faturamento',
    colors: ["#086bac", "#fbfcff"], legend: true %>
  </div>
  <div class="col-sm-6">
    <%= area_chart new_invoices_count_path, label: '# Recibos', legend: true, ytitle: '# Recibos' %>
  </div>
  <div class="col-sm-6">
    <%= line_chart new_invoices_company_path, label: 'Faturamento [valores em R$]', ytitle: 'Faturamento',
    colors: ["#086bac", "#fbfcff"], legend: true %>
  </div>
  <div class="col-sm-6">
    <%= column_chart new_invoices_sum_count_path, colors: ["#086bac", "#F25F5C"],
                    backgroundColor: ["F5EE9E"], legend: true, discrete: true %>
  </div>
</div>

app/views/invoices/_form.html.erb
<div class="col-xs-12">
<%= simple_form_for(@invoice) do |f| %>
  <div id="invoice-wrap">
    <%= f.error_notification %>
    <div class="row">
      <div class="col-xs-12">
        <h3 class="page-header">INVOICE<small class="pull-right">Date: <span class="invoice_header_date"></span></small></h3>
      </div><!-- /.col -->
    </div>

    <div class="row invoice-info">
      <div class="col-xs-4 invoice-col">
        From
        <address>
          <%= f.input_field :company, class: "form-control", id: "1" %>
          <input class="form-control" id= "2"  placeholder="address line 1" />
          <input class="form-control" id= "3"  placeholder="address line 2" />
          <input class="form-control" id= "4"  placeholder="phone number" />
          <input class="form-control" id= ""  placeholder="zip code" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        To
        <address>
          <%= f.input_field :contragent, class: "form-control", id: "5" %>
          <input class="form-control" id= "6"  placeholder="address line 1" />
          <input class="form-control" id= "7"  placeholder="address line 2" />
          <input class="form-control" id= "8"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        <form class="form-horizontal">

          <div class="form-group">
            <div class="col-xs-5"><label>Invoice #</label></div>
            <div class="col-xs-7 invoice_num"><span id="invoice_number"><%= (Invoice.last.present? ? (Invoice.last.id + 1) : 1) %></span></div>
          </div>
          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :date, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :date, class: "form-control datepicker", as: :string, id: "invoice_date" %></div>
          </div>

          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :currency, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :currency, id:"invoice_currency", class: "form-control" %></div>
          </div>


          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-5 invoice_space"><label>Amount due</label></div>
            <div class="col-xs-7 invoice_space bold" style="text-align:right; padding-top:7px"><span class="due">0.00</span><span class="subtotal_currency"></span></div>
          </div>
        </form>
      </div><!-- /.col -->
    </div><!-- /.row -->

    <div class="row">
      <div class="col-xs-12 table-responsive">
        <hr>
        <table class="table table-hover" id="items">

          <thead>
              <th class="item-name">Item</th>
              <th class="description">Description</th>
              <th class="unit">Unit Cost</th>
              <th class="quantity">Quantity</th>
              <th class="units">Price</th>
              <th class="no_print">Actions</th>
          </thead>

          <tbody>
            <tr class="item-row">
              <td><input class="form-control item_name" value="Item #1" /></td>
              <td><input class="form-control item_desc" value="Description" /></td>
              <td><input class="form-control cost" value="0.00" /></td>
              <td><input class="form-control qty" value="0" /></td>
              <td class="price_td"><span class="price"></span><span class="subtotal_currency"></span></td>
              <td class="delete_td"><a class="delete" href="javascript:;" title="Remove row"><span class="ti-close"></span></a></td>
            </tr>


            <tr id="hiderow">
              <td colspan="6"><a id="addrow" class="btn btn-success btn-sm" href="javascript:;" title="Add a row"><span class="ti-plus"></span>  Add a row</a></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6 col-xs-offset-6">
        <div class="table-responsive">
          <table class="table table-hover" id="totals">
            <tr>
              <th style="width:50%">Subtotal:</th>
              <td><span id="subtotal">0.00</span><span class="subtotal_currency"></span></td>
            </tr>
            <tr>
              <th>Tax:</th>
              <td><input id="9" class="form-control" value="0.00" /></td>
            </tr>
            <tr>
              <th>Total:</th>
              <td class="balance"><span class="due" id="invoice_total">0.00</span><span class="subtotal_currency"></span></td>
              <%=f.hidden_field :amount, id: "invoice_total1" %>
            </tr>
          </table>
        </div>
      </div><!-- /.col -->
    </div>




    <div class="row">
      <div class="col-sm-2 col-sm-offset-2">
        <%= f.input :image %>
      </div>
      <div class="col-sm-2 col-sm-offset-2">
        <%= f.input :resource %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 pull-left">
        <a class="btn btn-info btn-sm" id="invoice_button" data-toggle="modal" data-target="#invoice_modal">Show Invoice</a>
        <%= f.button :submit, 'Submit Payment', class: 'btn btn-warning btn-sm', id: "submit_invoice" %>
      </div>
    </div>

    <div id="terms">
      <h5>Terms</h5>
      <textarea id="10">Payment terms: net 30. Interest accrued at 1.5% per month thereafter.</textarea>
    </div>
  </div>
  <% end %>
</div>

<div class="modal fade" id="invoice_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" style="width:920px">
      <div class="container-fluid invoice_wrapper" style="margin:10px" id="print-me">
        <%= render 'invoice' %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" onclick="printDiv('print-me')">Print</button>
      </div>
    </div>
  </div>
</div>

app/views/invoices/_invoice.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="page-header">
      INVOICE
      <small class="pull-right">Date: <span class="invoice_header_date"></span></small>
      <button class="btn btn-primary" type="button" name="button"></button>
    </h3>
  </div><!-- /.col -->
</div>
                <!-- info row -->
<div class="row invoice-info">
  <div class="col-xs-4 invoice-col">
    From
    <address>
      <div id= "modal_1" class="bold"></div>
      <div id= "modal_2"></div>
      <div id= "modal_3"></div>
      <div id= "modal_4"></div>

    </address>
  </div><!-- /.col -->

  <div class="col-xs-4 invoice-col">
    To
    <address>
      <div id= "modal_5"></div>
      <div id= "modal_6"></div>
      <div id= "modal_7"></div>
      <div id= "modal_8"></div>
    </address>
  </div><!-- /.col -->

  <div class="col-xs-4 invoice-col">
    <form class="form-horizontal">
      <div class="form-group">
        <div class="col-xs-5"><label>Invoice #</label></div>
        <div class="col-xs-7"><p id="modal_invoice_number" class="pull-right"></p></div>
      </div>

      <div class="col-xs-12"></div>

      <div class="form-group">
        <div class="col-xs-4"><label>Date</label></div>
        <div class="col-xs-8"><span class="invoice_header_date pull-right"></span></div>
      </div>

      <div class="col-xs-12"></div>

      <div class="form-group">
        <div class="col-xs-5 invoice_space"><label>Amount due</label></div>
        <div class="col-xs-7 invoice_space bold" style="text-align:right"><span class="due">0.00</span><span class="subtotal_currency"></span></div>
      </div>
    </form>
  </div><!-- /.col -->
</div><!-- /.row -->

<div class="row">
	<div class="col-xs-12">
    <hr>
		<table class="table table-bordered" id="modal_items">
		  <thead>
		     <tr>
          <th class="item-name">Item</th>
          <th class="description">Description</th>
          <th class="unit">Unit Cost</th>
          <th class="quantity">Quantity</th>
          <th class="units">Price</th>
		     </tr>
		  </thead>
		  <tbody id="modal_tbody">
		  </tbody>
		</table>

	</div>
</div>

<div class="row">
	<div class="col-xs-6 col-xs-offset-6">
    <div class="">
      <table class="table" id="modal_totals">
        <tr>
          <th style="width:50%">Subtotal:</th>
          <td><span id="modal_subtotal"></span><span class="subtotal_currency"></span></td>
        </tr>
        <tr>
          <th>Tax:</th>
          <td><span id="modal_9"></span><span class="subtotal_currency"></span></td>
        </tr>
        <tr>
          <th>Total:</th>
          <td class="balance"><span class="due">0.00</span><span class="subtotal_currency"></span></td>
        </tr>
      </table>
    </div>
  </div><!-- /.col -->
</div>

<div id="modal_terms">
	<h5>Terms</h5>
	<span id="modal_10"></span>
</div>

app/views/invoices/edit.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <h3 class="panel-title">Editing Invoice</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Back', invoices_path, class: "btn btn-danger btn-sm" %>
        <%= link_to 'Show', invoice_path(@invoice), class: "btn btn-info btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
    <h1 class="page-header">
      Invoice Listing
      <%= link_to 'New Invoice', new_invoice_path, class: "btn btn-default btn-sm pull-right" %>
    </h1>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel panel-heading">
          <div class="container">
            <div class="col-md-2">
              <%= link_to 'New Invoice', new_invoice_path, class: "btn btn-default btn-sm" %>
            </div>

            <%= search_form_for @search, url: search_invoices_path, method: :post,
                                html:  {class: "form-inline col-md-8 col-me-offset-4"} do |f| %>
              <div class="input-daterange">
                <div class="col-md-2 col-md-offset-4">
                  <%= f.text_field :date_gteq, class: "form-control input-sm", placeholder: "Date >= to" %>
                </div>

                <div class="col-md-2">
                  <%= f.text_field :date_lteq, class: "form-control input-sm", placeholder: "Date <= to" %>
                </div>
              </div>
              <div class="col-md-2 col-md-offset-1 form-actions">
                <%= f.submit "Search", class: "btn btn-success btn-sm" %>
              </div>

            <% end %>
          </div>
        </div>


        <div class="panel panel-body">
          <table class="table table-hover table-bordered">
            <thead>
              <tr>
                <th>Company</th>
                <th>Contragent</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Date</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <% @invoices.each do |invoice| %>
              <tbody>
                <tr>
                  <td><%= invoice.company %></td>
                  <td><%= invoice.contragent %></td>
                  <td><%= invoice.amount %></td>
                  <td><%= invoice.currency %></td>
                  <td><%= invoice.date %></td>
                  <td><%= link_to 'Show', invoice_path(invoice), class: "btn btn-primary btn-sm"%></td>
                  <td><%= link_to 'Edit', edit_invoice_path(invoice), class: "btn btn-warning btn-sm"%></td>
                  <td><%= link_to 'Delete', invoice_path(invoice), method: :delete,
                                          class: "btn btn-danger btn-sm"%></td>
                </tr>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

  <%= render 'data' %>

app/views/invoices/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel panel-heading">
        <%= link_to 'Back', invoices_path, class: "btn btn-danger btn-sm" %>
      </div>
      <div class="panel panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/invoices/show.html.erb
<h1 class="page-header">
  Invoice #<%= @invoice.id %>
  <%= link_to 'Back', invoices_path, class: "btn btn-default pull-right" %>
</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Company</th>
              <th>Contragent</th>
              <th>Amount</th>
              <th>Currency</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= @invoice.company %></td>
              <td><%= @invoice.contragent %></td>
              <td><%= @invoice.amount %></td>
              <td><%= @invoice.currency %></td>
              <td><%= @invoice.date %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="panel-footer">

          <td><%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-warning btn-sm"%></td>
          <td><%= link_to 'Delete', invoice_path(@invoice), method: :delete,
                                  class: "btn btn-danger btn-sm"%></td>
      </div>
    </div>
  </div>
</div>