config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :details, only: [:edit, :update, :show]

  get '/new_invoices_sum', to: 'charts#new_invoices_sum'
  get '/new_invoices_count', to: 'charts#new_invoices_count'
  get '/new_invoices_company', to: 'charts#new_invoices_company'
  get '/new_invoices_sum_count', to: 'charts#new_invoices_sum_count'


  root 'pages#home'

  get '/test', to: 'pages#test'

  resources :invoices do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %> alert-dismissible fade-in">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar_top.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= link_to 'Invoices', root_path, class: "navbar-brand" %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Invoices', root_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
              <li>
                <%= link_to 'Minha Conta', detail_path(current_user.detail.id), class: 'btn btn-primary' %>
              </li>
            
            <li>
            <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Abrir Conta', new_user_registration_path, class: 'btn btn-primary' %>
            </li>
            <li>
              <%= link_to 'Entrar', new_user_session_path, class: 'btn btn-success' %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navvertical.html.erb
<div class="btn-group-vertical">
    <a href="#" class="btn btn-default">Button</a>
    <a href="#" class="btn btn-default">Button</a>
    <a href="#" class="btn btn-default">Button</a>
    <a href="#" class="btn btn-default">Button</a>
</div>