config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :details, only: [:edit, :update, :show]

  get '/new_invoices_sum', to: 'charts#new_invoices_sum'
  get '/new_invoices_count', to: 'charts#new_invoices_count'
  get '/new_invoices_company', to: 'charts#new_invoices_company'
  get '/new_invoices_sum_count', to: 'charts#new_invoices_sum_count'


  root 'pages#home'

  get '/test', to: 'pages#test'

  resources :invoices do
    collection do
      match 'search' => 'invoices#search', via: [:get, :post], as: :search
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/detail.rb
class Detail < ApplicationRecord
  has_one :user, inverse_of: :detail, dependent: :destroy
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  # def new
  #   @detail = current_user.create_detail
  # end
  #
  # def create
  #   @detail = current_user.build_detail(detail_params)
  #   if @detail.save
  #     redirect_to root_path
  #   else
  #     render 'new'
  #   end
  # end

  def edit
    @detail = Detail.find(params[:id])

  end

  def update
    @detail = Detail.find(params[:id])
    if @detail.update(detail_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
    @detail = current_user.detail
  end

  private

  def detail_params
    params.require(:detail).permit(:name, :birth_date, :user_id)
  end
end

app/views/details/_form.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-6">
            <h5>Minha Conta | <small>Dados</small></h5>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <%= simple_form_for(@detail, html: {class: 'form-horizontal'}) do |f| %>
            <div class="row">
              <div class="col-sm-8">
                <%= f.input :name, label: 'Nome', placeholder: "Nome"%>
              </div>
              <div class="col-sm-4">
                <%= f.input :birth_date, as: :string, input_html: { :class => "datepicker"}, label: 'Data Nascimento', placeholder: "Data de Nascimento"%>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-sm-12">
            <div class="btn-group pull-right">
              <%= button_tag type: 'submit', class: 'btn btn-mc-success mc-margin-r pull-right',
                            :'data-toggle' => 'tooltip', :'data-placement' => 'top', :title => 'Salvar' do %>
                <i class="fa fa-floppy-o fa-2x" aria-hidden="true"></i>
              <% end %>

              <%= link_to '<i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>'.html_safe, :back, class: 'btn btn-default mc-margin-r',
                            :'data-toggle' => 'tooltip', :'data-placement' => 'top', :title => 'Voltar' %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/details/edit.html.erb
<%= render 'form' %>

app/views/details/new.html.erb
<%= render 'form' %>

app/views/details/show.html.erb
<h1 class="page-header">
  This is my detail
  <span><%= link_to 'Editar', edit_detail_path(current_user.detail), class: 'btn btn-primary pull-right' %></span>
</h1>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <p><%= current_user.detail.name %></p>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <p><%= current_user.detail.birth_date %></p>
  </div>
</div>